name: "Generate dotenv file"
author: "Jacob Fredericksen"
description: "Action for generating a dotenv file based on a template file"
branding:
  icon: "file-plus"
  color: "red"
inputs:
  template-paths:
    description: "Filepath or space-delimited list of filepaths of the template file(s) used to generate the dotenv file"
    required: true
  output-path:
    description: "Filepath for the output file"
    required: false
    default: ".env"
  cache:
    description: "Boolean specifying whether to cache the output file ('true' or 'false')"
    required: false
    default: "true"
runs:
  using: "node16"
  main: "dist/index.js"
